### ISSUE TITLE
the availability of the code

### ISSUE THREAD

**Issue by arasharchor** [lxtGH/GALD-Net#1]
Hi, 

I am creating a new benchmark with fine-grained annotation in aerial imagery. In the paper, I am doing a heavy benchmark on state-of-the-art methods such as PSPNet, Deeplabv+, BiSeNet, DenseASSP and so on for semantic segmentation. I am wondering whether it is possible to train your algorithm on this data for the sake of benchmark with proper citation.

**Comment by lxtGH** [comment]
Hi ! @smajida  I also created a benchmark for cityscape dataset. Now, I have re-implemented nearly all the state-of-art semantic segmentation models on cityscape dataset(PSPnet, deeplabv3+, deeplabv3, DAnet, DenseASPP, Bi-Seg). All of the models and codes including our GALD-net will be released in this repo.

**Comment by gupta-abhay** [comment]
Hi,

Is there a timeline to the release? We are interested in using the model for some research.

**Comment by Shannongxn** [comment]
Hi,

Is there a timeline to the release? We are interested in using the model for some research too~

**Comment by smajida** [comment]
> Hi ! @smajida I also created a benchmark for cityscape dataset. Now, I have re-implemented nearly all the state-of-art semantic segmentation model on cityscape dataset(PSPnet, deeplabb3+, deeplabv3, DAnet, DenseASPP, ). All of the models and codes including our GALD-net will be released in this repo.

Hi @lxtGH thanks for your kind reply. I am waiting for the release of the code. We have received reviews for our paper (unfortunately without GALD-Net) and working on the rebuttal, but we could add it for the next version. I am also adding "Searching for Efficient Multi-Scale Architectures for Dense Image Prediction" which got 82.7% on CityScapes on our dataset which is called "SkyScapes" :)

**Comment by lxtGH** [comment]
I will release the code and model before BMVC.

**Comment by smajida** [comment]
@lxtGH thanks  a lot. My paper has been accepted in ICCV19 (https://github.com/smajida/SkyScapes), but unfortunately, I could not test your method on this dataset and today we are submitting the camera-ready version. Please let me know when you will release the code. Then I will add it to the next paper on SkyScapes.

**Comment by shipengai** [comment]
@lxtGH Hi, When do you plan to release the code and model?

**Comment by sahanalva** [comment]
@lxtGH Hi, When do you plan to release the code and model?

**Comment by lxtGH** [comment]
I have released the code and more models will be added in the fulture.
