### ISSUE TITLE
The availability of the code about "Dual Graph Convolutional Network for Semantic Segmentation" .

### ISSUE THREAD

**Issue by ZhuPeipei-CUHKSZ-TJUTCM** [lxtGH/GALD-Net#10]
I am very expect that you can release the code about "Dual Graph Convolutional Network for Semantic Segmentation". Thanks.

**Comment by qgh1223** [comment]
I also expect it.

**Comment by lxtGH** [comment]
@qgh1223 @username123062 Hi! Guys thanks for your interests. I will release the model file and ckpt within two weeks. If you want the model file, you can email me at: lxtpku@pku.edu.cn

**Comment by lxtGH** [comment]
@username123062 @qgh1223 Hi both codes and trained model are released. Thanks for your attention !
