### ISSUE TITLE
something wrong with trainning DualSeg

### ISSUE THREAD

**Issue by tist0bsc** [lxtGH/GALD-Net#16]

**Comment by tist0bsc** [comment]
sorry i just verified that the code stop in line 193: "deeplab.cuda()"

**Comment by lxtGH** [comment]
??? what is your specific question ?

**Comment by tist0bsc** [comment]
I'm sorry, I met something wrong when I was training ，but yesterday I found  out that it's a problem of my apex, it can't use more than 2 GPUs once time. If I modify the parameter "nproc_per_node" to 2 , the code runs well.So I edit the comment, because I can't find the "delete" button. Thks
