### ISSUE TITLE
Not able to download the pre-trained model from baidu pan

### ISSUE THREAD

**Issue by araomv** [lxtGH/GALD-Net#19]
Hi,

Thanks for the repo. 

I am trying to download the pre-trained weights of the model using Baidu Pan Link (https://pan.baidu.com/s/1MWzpkI3PwtnEl1LSOyLrLw). But there is no option to download the files. Is it possible to share models on google drive?

Thanks for your help

Regards,
Achuth

**Comment by lxtGH** [comment]
Hi! I upload the link of pretrained model in Google Drive. Please have a look
