### ISSUE TITLE
how to plot the error map?

### ISSUE THREAD

**Issue by YangParky** [lxtGH/GALD-Net#22]
![图片](https://user-images.githubusercontent.com/38532963/155524531-f7fab1ed-aea0-49cb-8eb3-82b0b26dcf7e.png)

**Comment by lxtGH** [comment]
https://github.com/NVIDIA/semantic-segmentation/blob/2f548ab30ab0d56e91de66a4dea4757a0c64e7e4/eval.py#L489
Please checkout this links for diff images generation.
