### ISSUE TITLE
Why do you downsample feature first and then input GA module? ( x = self.down(x)   x = self.long_relation(x))

### ISSUE THREAD

**Issue by kaigelee** [lxtGH/GALD-Net#24]
class GALDBlock(nn.Module):
    def forward(self, x):
        size = x.size()[2:]
        x = self.down(x)
        x = self.long_relation(x)
        # local attention
        x = F.interpolate(x,size=size, mode="bilinear", align_corners=True)
        res = x
        x = self.local_attention(x)
        return x + res

**Comment by kaigelee** [comment]
另外，local_attention返回的已经是 res1 + res2，也就是原始图+分配图了，为什么在GALDBlock中还要将返回值与原始图相加（x + res）呢？这样不是等于返回两倍的原始特征图了吗？

**Comment by lxtGH** [comment]
Hi! This is a simple residual design, which is also common in several previous work including CCNet, OCRNet.
