### ISSUE TITLE
GFF-Net

### ISSUE THREAD

**Issue by yyfyan** [lxtGH/GALD-Net#4]
你好，在GFF这篇论文的表1的对比实验中，SUM和Cat是先对Backbone的所有特征图进行1x1降维到256，然后sum/cat，最后再加两次3x3卷积。而FPN从公式来看，只用了最后一个FPN层，也即1/4的特征图，没有将1/32、1/16、1/8、1/4所有特征图进行融合。而GFF是将FPN的所有层进行Cat后进行预测，这个对比是否还合理呢。还是我理解错了，FPN如果只用1/4特征图，和sum也没多少区别了？
能否解答下疑惑呢，谢谢。

**Comment by yyfyan** [comment]
@lxtGH

**Comment by lxtGH** [comment]
Thanks for your interest: 
1. sum: sum up all the feature pyramids to perdict. 
2. Cat: concate all the feature pyramids to predict.
3. FPN: information from top to bottom and then concate all the feature pyramids to predict.
