### ISSUE TITLE
The use of 16bit images and stereo

### ISSUE THREAD

**Issue by kwea123** [lxtGH/GALD-Net#5]
On the [cityscapes score](https://www.cityscapes-dataset.com/anonymous-results/?id=5ee0f5098e160aa56db6e9ed01c5fbc73d4ac736b6b61751b50ad31067b0d5bd), it is shown that you use both 16bit images and stereo data, but I cannot find any explanation in the paper. Could you clarify why you use these data and their effect?

**Comment by lxtGH** [comment]
We use depth information for multi-scale inference for boosting performance. However, there is only 0.1 improvement. I will clarify this trick later in our journel paper.
