### ISSUE TITLE
请问一下什么时候公开源码呢 期待呀

### ISSUE THREAD

**Issue by WangboML** [lxtGH/GALD-Net#6]

**Comment by lxtGH** [comment]
Hi! We will release the code and models in November.

**Comment by myknowntime** [comment]
Yeah~!! November is coming!!!

**Comment by WangboML** [comment]
您好 还在期待您的源码呢 哈哈

**Comment by lxtGH** [comment]
Sorry for late reply, I am busy with other projects. I will release trained code in this week.
Codes have been released.
