### ISSUE TITLE
About the performance of GALD

### ISSUE THREAD

**Issue by dingguo1996** [lxtGH/GALD-Net#7]
Thanks for your work in semantic segmentation. I'm confused about the reason of worse performance with your galdnet in [https://github.com/speedinghzl/pytorch-segmentation-toolbox](url).

**Comment by lxtGH** [comment]
What are your setting and results?

**Comment by dingguo1996** [comment]
I just used the default setting and sync bn in [https://github.com/speedinghzl/pytorch-segmentation-toolbox/blob/master/run_local.sh](url), but only got 78.07 miou in the end.
