### ISSUE TITLE
I have encounter the problem KeyError: 'CascadeRelatioNet_res50' and I find DeeplabV3.py is void

### ISSUE THREAD

**Issue by Deeachain** [lxtGH/GALD-Net#8]
Hello，Thank you for sharing the code。
I run python train_distribute.py  ,encounter porblem as follows
`Traceback (most recent call last):
  File "train_distribute.py", line 262, in <module>
    main()
  File "train_distribute.py", line 157, in main
    deeplab = models.__dict__[args.arch](num_classes=args.num_classes, data_set=args.data_set)
KeyError: 'CascadeRelatioNet_res50'`

another question is 
DANet.py  DeeplabV3.py GloreNet.py .Why are they empty

**Comment by lxtGH** [comment]
I will update the model files and fix this bugs this weekend

**Comment by Deeachain** [comment]
Thank you very much!




| |
丁成
|
|
邮箱：dingcheng0107@163.com
|

签名由 网易邮箱大师 定制

On 01/03/2020 19:31, Latou wrote:

I will update the model files and fix this bugs this weekend

**Comment by lxtGH** [comment]
I have released the dual seg code and please check it .
